[options]
addons_path = C:\Program Files\Odoo 19.0.20260119\server\odoo\addons,C:\Users\SOULMATE PLUS IP\Documents\VTO\odoo-addons
db_host = localhost
db_port = 5432
db_user = openpg
db_password = openpgpwd
http_port = 8073
admin_passwd = admin
logfile = C:\Users\SOULMATE PLUS IP\Documents\VTO\odoo-local.log
